[project]
name = "drgt"
version = "0.1.0"
description = "Drug response prediction with Graph Transformer"
requires-python = ">=3.9, <3.12"
dependencies = [
    "numpy<2",
    "pandas",
    "torch",
    "torch-geometric",
    "scikit-learn",
    "tqdm",
    "pubchempy",
    "seaborn",
    "pyyaml",
    "packaging",
    "ipykernel",
    "rdkit-pypi; python_version < \"3.12\"",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["drGT"]
